// Wygenerowane na podstawie systematyki numerow seryjnych Gamet (numery seryjne.docx)
export interface LampType {
  name: string
  groupCode: string
  category: string
}

export const OTHER_LAMP_MODEL = 'Inny / nie wiem'

export const LAMP_TYPES: LampType[] = [
  { name: 'FALA 6 MAKROLED', groupCode: 'AA01', category: 'INNE' },
  { name: 'FALA 8 MAKROLED', groupCode: 'AA02', category: 'INNE' },
  { name: 'STEROWNIK FALA', groupCode: 'AA04', category: 'INNE' },
  { name: 'STEROWNIK LZ DELUX', groupCode: 'AA05', category: 'INNE' },
  { name: 'TARCZA PODŚWIETLANA LIZAK', groupCode: 'AA03', category: 'INNE' },
  { name: 'WYŚWIETLACZ JEDŹ ZA MNĄ /STOP', groupCode: 'AD01', category: 'WYŚWIETLACZE' },
  { name: 'WYŚWIETLACZ MATRYCOWY 8x60', groupCode: 'AD02', category: 'WYŚWIETLACZE' },
  { name: 'WYŚWIETLACZ MATRYCOWY 8x80', groupCode: 'AD03', category: 'WYŚWIETLACZE' },
  { name: 'WYŚWIETLACZ MATRYCOWY 12x60', groupCode: 'AD04', category: 'WYŚWIETLACZE' },
  { name: 'WYŚWIETLACZ MATRYCOWY INFOSYSTEM 8x80', groupCode: 'AD05', category: 'WYŚWIETLACZE' },
  { name: 'PANEL STERUJĄCY INFOSYSTEM', groupCode: 'AD06', category: 'WYŚWIETLACZE' },
  { name: 'PS2 AF', groupCode: 'AF01', category: 'AUTOFORM' },
  { name: 'SZYLD LED AF', groupCode: 'AF02', category: 'AUTOFORM' },
  { name: 'AMZ MBSN1-BB', groupCode: 'AK01', category: 'AMZ KUTNO' },
  { name: 'AMZ MBSN1-BE', groupCode: 'AK02', category: 'AMZ KUTNO' },
  { name: 'AMZ MBSN1 WA', groupCode: 'AK03', category: 'AMZ KUTNO' },
  { name: 'REFLEKTOR DALEKOSIĘŻNY S1', groupCode: 'AL01', category: 'OŚWIETLENIOWE' },
  { name: 'REFLEKTOR RĘCZNY SPOT LED', groupCode: 'AL02', category: 'OŚWIETLENIOWE' },
  { name: 'REFLEKTOR ROZPRASZAJĄCY S2', groupCode: 'AL03', category: 'OŚWIETLENIOWE' },
  { name: 'STARLIGHT', groupCode: 'AL04', category: 'OŚWIETLENIOWE' },
  { name: 'LED STRIP', groupCode: 'AL05', category: 'OŚWIETLENIOWE' },
  { name: 'PBX', groupCode: 'AP01', category: 'PODZESPOŁY' },
  { name: 'SXBN2011', groupCode: 'AP02', category: 'PODZESPOŁY' },
  { name: 'LO 1/1', groupCode: 'AR01', category: 'DROGOWE' },
  { name: 'LO 2/1', groupCode: 'AR02', category: 'DROGOWE' },
  { name: 'EVO LED TB2', groupCode: 'AT01', category: 'DOOKÓLNE' },
  { name: 'EVO LED TA1', groupCode: 'AT02', category: 'DOOKÓLNE' },
  { name: 'EVO LED TR 1', groupCode: 'AT03', category: 'DOOKÓLNE' },
  { name: 'MARTA KO', groupCode: 'AT04', category: 'DOOKÓLNE' },
  { name: 'MARTA KX', groupCode: 'AT05', category: 'DOOKÓLNE' },
  { name: 'MARTA LED LL24', groupCode: 'AT06', category: 'DOOKÓLNE' },
  { name: 'SLO3 LED LL24', groupCode: 'AT07', category: 'DOOKÓLNE' },
  { name: 'SLO3 LED', groupCode: 'AT08', category: 'DOOKÓLNE' },
  { name: 'SLO3O', groupCode: 'AT09', category: 'DOOKÓLNE' },
  { name: 'SLO3X', groupCode: 'AT10', category: 'DOOKÓLNE' },
  { name: 'SLO6 DUO', groupCode: 'AT11', category: 'DOOKÓLNE' },
  { name: 'SLO5', groupCode: 'AT12', category: 'DOOKÓLNE' },
  { name: 'WAS INTEGRO CB HTFL', groupCode: 'AW01', category: 'WAS' },
  { name: 'WAS INTEGRO CB HTFR', groupCode: 'AW02', category: 'WAS' },
  { name: 'WAS INTEGRO CB HTRL', groupCode: 'AW03', category: 'WAS' },
  { name: 'WAS INTEGRO CB HTRR', groupCode: 'AW04', category: 'WAS' },
  { name: 'WAS INTEGRO CB XFC', groupCode: 'AW05', category: 'WAS' },
  { name: 'WAS INTEGRO CB XFL', groupCode: 'AW06', category: 'WAS' },
  { name: 'WAS INTEGRO CB XFR', groupCode: 'AW07', category: 'WAS' },
  { name: 'WAS INTEGRO PS 2', groupCode: 'AW08', category: 'WAS' },
  { name: 'WAS INTEGRO PS2 PB', groupCode: 'AW09', category: 'WAS' },
  { name: 'WAS INTEGRO DB HTFL', groupCode: 'AW10', category: 'WAS' },
  { name: 'WAS INTEGRO DB HTFR', groupCode: 'AW11', category: 'WAS' },
  { name: 'WAS INTEGRO DB HTRL', groupCode: 'AW12', category: 'WAS' },
  { name: 'WAS INTEGRO DB HTRR', groupCode: 'AW13', category: 'WAS' },
  { name: 'WAS INTEGRO DB XFL', groupCode: 'AW14', category: 'WAS' },
  { name: 'WAS INTEGRO DB XFR', groupCode: 'AW15', category: 'WAS' },
  { name: 'WAS INTEGRO DR HTFL', groupCode: 'AW16', category: 'WAS' },
  { name: 'WAS INTEGRO DR HTFR', groupCode: 'AW17', category: 'WAS' },
  { name: 'WAS INTEGRO DR HTRL', groupCode: 'AW18', category: 'WAS' },
  { name: 'WAS INTEGRO DR HTRR', groupCode: 'AW19', category: 'WAS' },
  { name: 'WAS INTEGRO DR XFL', groupCode: 'AW20', category: 'WAS' },
  { name: 'WAS INTEGRO DR XFR', groupCode: 'AW21', category: 'WAS' },
  { name: 'WAS INTEGRO BB HTFL', groupCode: 'AW22', category: 'WAS' },
  { name: 'WAS INTEGRO BB HTFR', groupCode: 'AW23', category: 'WAS' },
  { name: 'WAS INTEGRO BB HTRL', groupCode: 'AW24', category: 'WAS' },
  { name: 'WAS INTEGRO BB HTRR', groupCode: 'AW25', category: 'WAS' },
  { name: 'WAS INTEGRO BB XFC', groupCode: 'AW26', category: 'WAS' },
  { name: 'WAS INTEGRO BB XFL', groupCode: 'AW27', category: 'WAS' },
  { name: 'WAS INTEGRO BB XFR', groupCode: 'AW28', category: 'WAS' },
  { name: 'WAS INTEGRO BR HTFL', groupCode: 'AW29', category: 'WAS' },
  { name: 'WAS INTEGRO BR HTFR', groupCode: 'AW30', category: 'WAS' },
  { name: 'WAS INTEGRO BR HTRL', groupCode: 'AW31', category: 'WAS' },
  { name: 'WAS INTEGRO BR HTRR', groupCode: 'AW32', category: 'WAS' },
  { name: 'WAS INTEGRO BR XFC', groupCode: 'AW33', category: 'WAS' },
  { name: 'WAS INTEGRO BR XFL', groupCode: 'AW34', category: 'WAS' },
  { name: 'WAS INTEGRO BR XFR', groupCode: 'AW35', category: 'WAS' },
  { name: 'WAS STEUERMODUL SPRINTER BM907', groupCode: 'AW36', category: 'WAS' },
  { name: 'WAS INTEGRO SB HTFL', groupCode: 'AW37', category: 'WAS' },
  { name: 'WAS INTEGRO SB HTFR', groupCode: 'AW38', category: 'WAS' },
  { name: 'WAS INTEGRO SB TL', groupCode: 'AW39', category: 'WAS' },
  { name: 'WAS INTEGRO SB TR', groupCode: 'AW40', category: 'WAS' },
  { name: 'WAS INTEGRO SB XFC', groupCode: 'AW41', category: 'WAS' },
  { name: 'WAS INTEGRO SB XFL', groupCode: 'AW42', category: 'WAS' },
  { name: 'WAS INTEGRO SB XFR', groupCode: 'AW43', category: 'WAS' },
  { name: 'WAS INTEGRO NB HTFL', groupCode: 'AW44', category: 'WAS' },
  { name: 'WAS INTEGRO NB HTFR', groupCode: 'AW45', category: 'WAS' },
  { name: 'WAS INTEGRO NB TL', groupCode: 'AW46', category: 'WAS' },
  { name: 'WAS INTEGRO NB TR', groupCode: 'AW47', category: 'WAS' },
  { name: 'WAS INTEGRO NB XFC', groupCode: 'AW48', category: 'WAS' },
  { name: 'WAS INTEGRO NB XFL', groupCode: 'AW49', category: 'WAS' },
  { name: 'WAS INTEGRO NB XFR', groupCode: 'AW50', category: 'WAS' },
  { name: 'WAS INTEGRO NB HTRL', groupCode: 'AW51', category: 'WAS' },
  { name: 'WAS INTEGRO NB HTRR', groupCode: 'AW52', category: 'WAS' },
  { name: 'EM-21', groupCode: 'AV01', category: 'WISS' },
  { name: 'LED 12/24', groupCode: 'AX01', category: 'KIERUNKOWE' },
  { name: 'MAKROLED LL8', groupCode: 'AX02', category: 'KIERUNKOWE' },
  { name: 'MAKROLED', groupCode: 'AX03', category: 'KIERUNKOWE' },
  { name: 'SLIM LED H', groupCode: 'AX04', category: 'KIERUNKOWE' },
  { name: 'SLIM LED V', groupCode: 'AX05', category: 'KIERUNKOWE' },
  { name: 'MAKROLED 2', groupCode: 'AX06', category: 'KIERUNKOWE' },
  { name: 'COMBOLED', groupCode: 'AX07', category: 'KIERUNKOWE' },
  { name: 'LAMPA ZESPOLONA', groupCode: 'CL01', category: 'LAMPY ZESPOLONE' },
  { name: 'GENERATOR GAM 150N', groupCode: 'SA01', category: 'GENERATORY' },
  { name: 'GENERATOR GAM 300N', groupCode: 'SA02', category: 'GENERATORY' },
  { name: 'GŁOŚNIK GAM 200', groupCode: 'SS01', category: 'GŁOŚNIKI' },
  { name: 'GŁOŚNIK GAM 150', groupCode: 'SS02', category: 'GŁOŚNIKI' },
]

export function getLampType(groupCode: string): LampType | undefined {
  return LAMP_TYPES.find((t) => t.groupCode === groupCode)
}
